"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
type Company={id:string,name:string,status:string,cash:number,tick_number:number,goal:string};
type Row={id:string;[key:string]:unknown};
export default function Page(){
 const [c,setC]=useState<Company|null>(null),[data,setData]=useState<Record<string,Row[]>>({}),[finance,setFinance]=useState<Record<string,number>>({});
 async function refresh(id:string){setC(await (await fetch(API+"/companies/"+id)).json());const keys=["activity","events","customers","meetings","actions","memory"];const pairs=await Promise.all(keys.map(async k=>[k,await (await fetch(API+"/companies/"+id+"/"+k)).json()] as const));setData(Object.fromEntries(pairs));setFinance(await (await fetch(API+"/companies/"+id+"/finance")).json())}
 useEffect(()=>{if(!c)return;let ws:WebSocket|undefined,t:ReturnType<typeof setTimeout>;const connect=()=>{ws=new WebSocket(API.replace(/^http/,"ws")+"/ws/companies/"+c.id+"/activity");ws.onmessage=e=>setData(x=>({...x,activity:JSON.parse(e.data)}));ws.onclose=()=>{t=setTimeout(connect,1500)}};connect();return()=>{clearTimeout(t);ws?.close()}},[c?.id]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const body={name:f.get("name"),industry:f.get("industry"),capital:Number(f.get("capital")),goal:f.get("goal"),horizon_days:90,autonomy:"SEMI_AUTONOMOUS",risk_tolerance:"MEDIUM"};const x=await (await fetch(API+"/companies",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)})).json();await refresh(x.id)}
 async function act(path:string){if(!c)return;await fetch(API+"/companies/"+c.id+"/"+path,{method:"POST"});await refresh(c.id)}
 const label=(r:Row)=>String(r.name||r.type||r.action||r.agenda||r.layer||r.status||r.id);
 return <main className="shell"><h1>BIONIC <span className="accent">AI COMPANY OS</span></h1><p className="muted">Persistent autonomous-company runtime.</p>{!c?<section className="card"><h2>Create company</h2><form className="form" onSubmit={create}><input name="name" placeholder="Company name" required/><input name="industry" placeholder="Industry" required/><input name="capital" type="number" defaultValue="50000"/><input name="goal" placeholder="Main goal" required/><button className="btn">Create & spawn team</button></form></section>:<><div className="grid"><div className="card"><b>Status</b><h2>{c.status}</h2></div><div className="card"><b>Ledger cash</b><h2>{Number(finance.cash||0).toLocaleString()} PLN</h2></div><div className="card"><b>P&amp;L</b><h2>{Number(finance.profit||0).toLocaleString()} PLN</h2></div></div><p><button className="btn" onClick={()=>act(c.status==="PAUSED"?"start":"pause")}>{c.status==="PAUSED"?"Start":"Pause"}</button> <button className="btn" onClick={()=>act("tick")}>Run tick</button></p><div className="grid">{["events","customers","meetings","actions","memory"].map(k=><section className="card" key={k}><h2>{k}</h2>{(data[k]||[]).slice(0,8).map(r=><div className="row" key={r.id}>{label(r)}</div>)}</section>)}</div><section className="card"><h2>Live Activity</h2><div className="feed">{(data.activity||[]).map(a=><div className="row" key={a.id}><b>{String(a.action)}</b> <span className="muted">{String(a.detail||"")}</span></div>)}</div></section></>}</main>
}