import enum,uuid
from datetime import datetime,timezone
from sqlalchemy import String,Text,DateTime,ForeignKey,Enum,Float,Integer,JSON,Index,Boolean,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from .db import Base
def now(): return datetime.now(timezone.utc)
class CompanyStatus(str,enum.Enum): PAUSED="PAUSED"; REALTIME="REALTIME"; FAST="FAST"; SIMULATION="SIMULATION"
class Autonomy(str,enum.Enum): MANUAL="MANUAL"; SEMI_AUTONOMOUS="SEMI_AUTONOMOUS"; AUTONOMOUS="AUTONOMOUS"
class TaskStatus(str,enum.Enum): BACKLOG="BACKLOG"; TODO="TODO"; IN_PROGRESS="IN_PROGRESS"; REVIEW="REVIEW"; BLOCKED="BLOCKED"; DONE="DONE"; CANCELLED="CANCELLED"
class Priority(str,enum.Enum): LOW="LOW"; MEDIUM="MEDIUM"; HIGH="HIGH"; CRITICAL="CRITICAL"
class Stamp:
    created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False)
    updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now,nullable=False)
class Company(Stamp,Base):
    __tablename__="companies"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4)
    name:Mapped[str]=mapped_column(String(160)); industry:Mapped[str]=mapped_column(String(160)); capital:Mapped[float]=mapped_column(Float); cash:Mapped[float]=mapped_column(Float); goal:Mapped[str]=mapped_column(Text); horizon_days:Mapped[int]=mapped_column(Integer); autonomy:Mapped[Autonomy]=mapped_column(Enum(Autonomy)); risk_tolerance:Mapped[str]=mapped_column(String(32)); status:Mapped[CompanyStatus]=mapped_column(Enum(CompanyStatus),default=CompanyStatus.PAUSED); speed:Mapped[int]=mapped_column(Integer,default=1); tick_number:Mapped[int]=mapped_column(Integer,default=0)
class Agent(Stamp,Base):
    __tablename__="agents"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); name:Mapped[str]=mapped_column(String(120)); position:Mapped[str]=mapped_column(String(120)); department:Mapped[str]=mapped_column(String(120)); role_description:Mapped[str]=mapped_column(Text,default=""); personality:Mapped[dict]=mapped_column(JSON,default=dict); skills:Mapped[list]=mapped_column(JSON,default=list); goals:Mapped[list]=mapped_column(JSON,default=list); kpis:Mapped[dict]=mapped_column(JSON,default=dict); status:Mapped[str]=mapped_column(String(32),default="ACTIVE"); manager_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); permission_level:Mapped[int]=mapped_column(Integer,default=1); knowledge_scope:Mapped[list]=mapped_column(JSON,default=list)
class Task(Stamp,Base):
    __tablename__="tasks"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); title:Mapped[str]=mapped_column(String(240)); description:Mapped[str]=mapped_column(Text,default=""); creator_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); assignee_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); parent_task_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("tasks.id",ondelete="SET NULL"),nullable=True); priority:Mapped[Priority]=mapped_column(Enum(Priority),default=Priority.MEDIUM); status:Mapped[TaskStatus]=mapped_column(Enum(TaskStatus),default=TaskStatus.TODO); deadline:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); estimated_effort:Mapped[float|None]=mapped_column(Float,nullable=True); actual_effort:Mapped[float|None]=mapped_column(Float,nullable=True); dependencies:Mapped[list]=mapped_column(JSON,default=list); blocked_reason:Mapped[str|None]=mapped_column(Text,nullable=True); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class Channel(Stamp,Base):
    __tablename__="channels"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); name:Mapped[str]=mapped_column(String(80)); allowed_departments:Mapped[list]=mapped_column(JSON,default=list)
class Message(Base):
    __tablename__="messages"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); channel_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("channels.id",ondelete="CASCADE"),index=True); sender_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); content:Mapped[str]=mapped_column(Text); thread_id:Mapped[uuid.UUID|None]=mapped_column(nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)
class Decision(Base):
    __tablename__="decisions"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); title:Mapped[str]=mapped_column(String(240)); problem:Mapped[str]=mapped_column(Text); context:Mapped[dict]=mapped_column(JSON,default=dict); options:Mapped[list]=mapped_column(JSON,default=list); participants:Mapped[list]=mapped_column(JSON,default=list); arguments:Mapped[dict]=mapped_column(JSON,default=dict); risk:Mapped[str]=mapped_column(String(32)); cost:Mapped[float]=mapped_column(Float,default=0); expected_outcome:Mapped[str]=mapped_column(Text); final_decision:Mapped[str]=mapped_column(Text); decided_by:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); result:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Activity(Base):
    __tablename__="activities"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); agent_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); action:Mapped[str]=mapped_column(String(120)); module:Mapped[str]=mapped_column(String(120)); status:Mapped[str]=mapped_column(String(32),default="OK"); detail:Mapped[str]=mapped_column(Text); duration_ms:Mapped[int]=mapped_column(Integer,default=0); error:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)
class LLMUsage(Base):
    __tablename__="llm_usage"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); provider:Mapped[str]=mapped_column(String(80)); model:Mapped[str]=mapped_column(String(120)); agent_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); task_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("tasks.id",ondelete="SET NULL"),nullable=True); prompt_tokens:Mapped[int]=mapped_column(Integer); completion_tokens:Mapped[int]=mapped_column(Integer); cost:Mapped[float]=mapped_column(Float); latency:Mapped[int]=mapped_column(Integer); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
Index("ix_tasks_company_status",Task.company_id,Task.status)

class Action(Base):
    __tablename__="actions"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); agent_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("agents.id",ondelete="CASCADE"),index=True); type:Mapped[str]=mapped_column(String(80)); payload:Mapped[dict]=mapped_column(JSON,default=dict); risk_level:Mapped[str]=mapped_column(String(32),default="LOW"); requires_approval:Mapped[bool]=mapped_column(default=False); status:Mapped[str]=mapped_column(String(32),default="PROPOSED"); result:Mapped[dict]=mapped_column(JSON,default=dict); idempotency_key:Mapped[str|None]=mapped_column(String(160),nullable=True,unique=True); retry_count:Mapped[int]=mapped_column(Integer,default=0); max_retries:Mapped[int]=mapped_column(Integer,default=3); failure_reason:Mapped[str|None]=mapped_column(Text,nullable=True); approved_by:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); queued_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); started_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Memory(Base):
    __tablename__="memories"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); agent_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="CASCADE"),nullable=True,index=True); layer:Mapped[str]=mapped_column(String(40)); content:Mapped[str]=mapped_column(Text); importance:Mapped[float]=mapped_column(Float,default=0.5); metadata_:Mapped[dict]=mapped_column("metadata",JSON,default=dict); source:Mapped[str]=mapped_column(String(80),default="SYSTEM"); customer_id:Mapped[uuid.UUID|None]=mapped_column(nullable=True); event_id:Mapped[uuid.UUID|None]=mapped_column(nullable=True); task_id:Mapped[uuid.UUID|None]=mapped_column(nullable=True); decision_id:Mapped[uuid.UUID|None]=mapped_column(nullable=True); meeting_id:Mapped[uuid.UUID|None]=mapped_column(nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)
class CompanyAccount(Base):
    __tablename__="company_accounts"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),unique=True,index=True); currency:Mapped[str]=mapped_column(String(3),default="PLN"); balance:Mapped[float]=mapped_column(Float,default=0); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Transaction(Base):
    __tablename__="transactions"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); account_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("company_accounts.id",ondelete="CASCADE"),index=True); type:Mapped[str]=mapped_column(String(20)); category:Mapped[str]=mapped_column(String(80)); amount:Mapped[float]=mapped_column(Float); description:Mapped[str]=mapped_column(Text); simulated:Mapped[bool]=mapped_column(default=False); status:Mapped[str]=mapped_column(String(20),default="POSTED"); reference_type:Mapped[str|None]=mapped_column(String(80),nullable=True); reference_id:Mapped[uuid.UUID|None]=mapped_column(nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)

class Customer(Stamp,Base):
    __tablename__="customers"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); name:Mapped[str]=mapped_column(String(180)); status:Mapped[str]=mapped_column(String(32),default="PROSPECT"); segment:Mapped[str]=mapped_column(String(80),default="default"); assigned_agent_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); context:Mapped[dict]=mapped_column(JSON,default=dict)
class Contact(Base):
    __tablename__="contacts"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); customer_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("customers.id",ondelete="CASCADE"),index=True); name:Mapped[str]=mapped_column(String(160)); email:Mapped[str|None]=mapped_column(String(240),nullable=True); role:Mapped[str|None]=mapped_column(String(120),nullable=True)
class CustomerInteraction(Base):
    __tablename__="customer_interactions"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); customer_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("customers.id",ondelete="CASCADE"),index=True); agent_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); channel:Mapped[str]=mapped_column(String(40)); direction:Mapped[str]=mapped_column(String(20)); content:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)
class CustomerNote(Base):
    __tablename__="customer_notes"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); customer_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("customers.id",ondelete="CASCADE"),index=True); agent_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); content:Mapped[str]=mapped_column(Text); important:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Event(Base):
    __tablename__="events"; __table_args__=(UniqueConstraint("company_id","idempotency_key",name="uq_event_company_key"),)
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); agent_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("agents.id",ondelete="SET NULL"),nullable=True); customer_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey("customers.id",ondelete="SET NULL"),nullable=True); type:Mapped[str]=mapped_column(String(80),index=True); priority:Mapped[str]=mapped_column(String(20),default="MEDIUM"); status:Mapped[str]=mapped_column(String(32),default="PENDING",index=True); source:Mapped[str]=mapped_column(String(80),default="INTERNAL"); payload:Mapped[dict]=mapped_column(JSON,default=dict); idempotency_key:Mapped[str]=mapped_column(String(160)); attempts:Mapped[int]=mapped_column(Integer,default=0); max_retries:Mapped[int]=mapped_column(Integer,default=3); error:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True); processed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class Meeting(Stamp,Base):
    __tablename__="meetings"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); owner_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("agents.id",ondelete="CASCADE")); type:Mapped[str]=mapped_column(String(40),default="REVIEW"); agenda:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String(32),default="SCHEDULED"); summary:Mapped[str|None]=mapped_column(Text,nullable=True); context:Mapped[dict]=mapped_column(JSON,default=dict)
class MeetingParticipant(Base):
    __tablename__="meeting_participants"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); meeting_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("meetings.id",ondelete="CASCADE"),index=True); agent_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("agents.id",ondelete="CASCADE")); role:Mapped[str]=mapped_column(String(40),default="PARTICIPANT")
class MeetingContribution(Base):
    __tablename__="meeting_contributions"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); meeting_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("meetings.id",ondelete="CASCADE"),index=True); agent_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("agents.id",ondelete="CASCADE")); content:Mapped[str]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ActionAttempt(Base):
    __tablename__="action_attempts"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); action_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("actions.id",ondelete="CASCADE"),index=True); attempt:Mapped[int]=mapped_column(Integer); status:Mapped[str]=mapped_column(String(32)); error:Mapped[str|None]=mapped_column(Text,nullable=True); started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); finished_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class Budget(Base):
    __tablename__="budgets"
    id:Mapped[uuid.UUID]=mapped_column(primary_key=True,default=uuid.uuid4); company_id:Mapped[uuid.UUID]=mapped_column(ForeignKey("companies.id",ondelete="CASCADE"),index=True); category:Mapped[str]=mapped_column(String(80)); limit_amount:Mapped[float]=mapped_column(Float); period:Mapped[str]=mapped_column(String(20),default="MONTHLY"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
